sprint 15
ArseniyBeglov/java-shareit pull request #3
Opened 2023-02-09 16:19 UTC by ArseniyBeglov

2023-02-09 17:06 UTC, ArseniyBeglov commented
![image](https://user-images.githubusercontent.com/97414762/217886171-59d59c06-e1b9-4e7b-b35e-0ccb67b83410.png)
не понимаю что не так, все тесты на компе проходят

2023-02-09 19:28 UTC, EugeneLenkevich requested changes
Привет,  Арсений, спасибо за PR

В целом все супер, тесты впечатляют :)
Отметил всего пару небольших косметических моментов, посмотри комментарии ниже, пожалуйста

2023-02-09 19:28 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +            throw new ValidateException("not positive");
Как мне кажется пользователю не совсем понятно по сообщению что именно пошло не так, с какой именно переменной проблема - с from или с size  :)

2023-02-09 19:28 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/booking/service/BookingServiceImpl.java
> +                            pageable, LocalDateTime.now(), LocalDateTime.now());
Как мне кажется pageable лучше ставить последним параметром в сигнатуре метода, все таки это вспомогательная вещь не несущая какого то бизнес-смысла, но, с другой стороны, переделывать много и толку от этого будет не очень. В общем,  оставим это по желанию :)

2023-02-09 19:28 UTC, EugeneLenkevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemMapperImpl.java
> +    public static ItemDtoRequests toDtoForRequest(Item item) {
Тут static не нужен, это же спринговый бин, к тому же другие методы не статические :)

2023-02-09 19:36 UTC, EugeneLenkevich commented
> не понимаю что не так, все тесты на компе проходят

это лучше сразу к наставнику

2023-02-12 04:59 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-02-15 14:05 UTC, merged